spring:
  profiles:  postgres-r2dbc
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/reservation
    username: postgres
    password: secret

logging.level:
  org.springframework.data.r2dbc: DEBUG
