spring:
  profiles:
    active: postgres
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/postgres
    username: postgres
    password: secret

logging.level:
  org.springframework.data.r2dbc: DEBUG