spring:
  profiles:
    active: postgres
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: create

logging.level:
  org.springframework.data.r2dbc: DEBUG


## Spring Boot configuration
#spring:
#  profiles:
#    active: default
#  # Security configuration
#  security:
#    user:
#      name: user
#      password: user
#  # Database
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/resevation
#    username: postgres
#    password: secret
#  # JPA properties
#  jpa:
#    hibernate:
#      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true
## Logger configuration
#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#  level:
#    org.springframework: info
#    org.hibernate: debug
## Server configuration
#server:
#  port: 8080 #set your port